apiVersion: apps.wandb.com/v1
kind: WeightsAndBiases
metadata:
  labels:
    app.kubernetes.io/name: weightsandbiases
    app.kubernetes.io/instance: wandb
    wandb.ai/console-default: "true"
  name: wandb
spec:
  release:
    url: https://charts.wandb.ai
    name: operator-wandb
    version: 0.1.0
  config: {}
