---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.wandb.com
  resources:
  - weightsandbiases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.wandb.com
  resources:
  - weightsandbiases/finalizers
  verbs:
  - update
- apiGroups:
  - apps.wandb.com
  resources:
  - weightsandbiases/status
  verbs:
  - get
  - patch
  - update
