# permissions for end users to edit weightsandbiases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: weightsandbiases-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: weightsandbiases-editor-role
rules:
  - apiGroups:
      - apps.wandb.com
    resources:
      - weightsandbiases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps.wandb.com
    resources:
      - weightsandbiases/status
    verbs:
      - get
